# =============================================================================
#
# - This is part of Lifamily Library (Wiki) project
#
# - Copyright (C) 2010-2021     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================
# Default host variables
# =================
[build_local]
localhost   ansible_connection=local

[build_remote]
xx.xx.xx.xx   ansible_connection=ssh    ansible_user=root

[in_target:vars]
ansible_python_interpreter=/usr/bin/python3

[in_target:children]
build_local