# =============================================================================
#
# - This is part of Lifamily Library (Wiki) project
#
# - Copyright (C) 2010-2021     George Li <yongxinl@outlook.com>
#
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: configuring Web server and PHP environment
  block:
      - lineinfile:
            dest: "/etc/hosts"
            line: '127.0.0.1  {{ mediawiki_server | replace("https","") | replace("http","") | replace(":","") | replace("//","") }}'
            state: present
      - lineinfile:
            dest: "/etc/php/{{ php_ver }}/fpm/php.ini"
            regexp: "{{ item.regxp }}"
            line: "{{ item.line }}"
            state: present
        with_items:
            - { regxp: "^post_max_size.*", line: "post_max_size = 256M" }
            - {
                  regxp: "^upload_max_filesize.*",
                  line: "upload_max_filesize = 256M",
              }
            - { regxp: "^allow_url_fopen.*", line: "allow_url_fopen = off" }
            - {
                  regxp: "^session.use_trans_sid.*",
                  line: "session.use_trans_sid = 0",
              }
            - { regxp: "^;opcache.enable.*", line: "opcache.enable = 1" }
            - {
                  regxp: "^;opcache.enable_cli.*",
                  line: "opcache.enable_cli = 1",
              }
            - {
                  regxp: "^;opcache.memory_consumption.*",
                  line: "opcache.;opcache.memory_consumption = 64",
              }
            - {
                  regxp: "^;opcache.interned_strings_buffer.*",
                  line: "opcache.interned_strings_buffer = 8",
              }
            - {
                  regxp: "^;opcache.max_accelerated_files.*",
                  line: "opcache.max_accelerated_files = 8000",
              }
            - {
                  regxp: "^;opcache.max_wasted_percentage.*",
                  line: "opcache.max_wasted_percentage = 5",
              }
            - {
                  regxp: "^;opcache.validate_timestamps.*",
                  line: "opcache.validate_timestamps = 1",
              }
            - {
                  regxp: "^;opcache.revalidate_freq.*",
                  line: "opcache.revalidate_freq = 60",
              }
            - {
                  regxp: "^;opcache.fast_shutdown.*",
                  line: "opcache.fast_shutdown = 1",
              }

- name: configuring MySQL user and database
  block:
      - command: /usr/bin/openssl rand -base64 16
        args:
            chdir: "{{ mediawiki_root }}"
        register: wiki_db_passwd
      - mysql_user:
            name: "{{ mediawiki_db_user }}"
            login_user: root
            login_password: "{{ target_root_password }}"
            state: absent
      - mysql_db:
            name: "{{ mediawiki_db_name }}"
            login_user: root
            login_password: "{{ target_root_password }}"
            state: absent
      - mysql_user:
            name: "{{ mediawiki_db_user }}"
            login_user: root
            login_password: "{{ target_root_password }}"
            password: "{{ wiki_db_passwd.stdout }}"
            priv: "{{ mediawiki_db_name }}.*:ALL"
            state: present
      - mysql_db:
            name: "{{ mediawiki_db_name }}"
            login_user: root
            login_password: "{{ target_root_password }}"
            collation: "utf8_general_ci"
            encoding: "utf8"
            state: present

- name: initialize {{ install_role_name }} database
  block:
      - service:
            name: ntp
            state: stopped
      - shell: "{{ item }}"
        args:
            chdir: "{{ mediawiki_root }}"
        with_items:
            - date --set '{{ mediawiki_startdate }}'
            - "php {{ mediawiki_root }}/maintenance/install.php \
              --dbname {{ mediawiki_db_name }} \
              --dbpass '{{ wiki_db_passwd.stdout }}' \
              --dbprefix ljmw_ \
              --dbserver localhost \
              --dbtype mysql \
              --dbuser {{ mediawiki_db_user }} \
              --installdbuser {{ mediawiki_db_user }} \
              --installdbpass '{{ wiki_db_passwd.stdout }}' \
              --pass '{{ mediawiki_admin_password }}' \
              --scriptpath /{{ mediawiki_ScriptPath }} \
              --server {{ mediawiki_server }} \
              {{ mediawiki_sitename | replace(' ','') }} \
              {{ mediawiki_admin_user }}"
            - ntpdate 0.au.pool.ntp.org
      - template:
            src: "{{ item.name }}"
            dest: "{{ item.dest }}"
            owner: root
            group: root
            mode: "{{ item.mode|default('0644') }}"
            backup: yes
        with_items:
            - "{{ mediawiki_configuration }}"

- name: Do maintenance after configuration
  block:
      - shell: "{{ item }}"
        args:
            chdir: "{{ mediawiki_root }}"
        with_items:
            - php maintenance/update.php --quick --force
      - service:
            name: ntp
            state: restarted
      - service:
            name: nginx
            state: restarted
