# =============================================================================
#
# - This is part of Lifamily Library (Wiki) project
#
# - Copyright (C) 2010-2021     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: install required package and setup directory for {{ install_role_nae }}
  block:
      - package:
            name: "{{ item }}"
            state: present
        register: install_pkgs
        until: install_pkgs|success
        retries: 2
        delay: 5
        with_items: "{{ mediawiki_base_packages }}"
        when: inst_status.stat.exists == True
      - file:
            path: "{{ mediawiki_root.split('/')[0:-1]|join('/') }}"
            state: directory
            mode: 0644

- name: install {{ install_role_name }} Core from repository
  block:
      - git:
            repo: "https://gerrit.wikimedia.org/r/p/mediawiki/core.git"
            dest: "{{ mediawiki_root }}"
            version: "{{ mediawiki_version }}"
            depth: 1
            force: yes
            update: yes
      - get_url:
            url: "https://getcomposer.org/installer"
            dest: "{{ mediawiki_root }}/composer-setup.php"
      - command: "{{ item }} chdir={{ mediawiki_root }}"
        with_items:
            - php composer-setup.php
            - php -r "unlink('composer-setup.php');"
      - command: "{{ item }}
            chdir={{ mediawiki_root }}"
        with_items:
            - php {{ mediawiki_root }}/composer.phar install --no-dev

- name: install Extensions and Skins from repository
  block:
      - shell: "{{ item }}
            chdir={{ mediawiki_root }}"
        with_items:
            - find skins/* -maxdepth 1 ! -name 'README' | xargs rm -rf
            - find extensions/* -maxdepth 1 ! -name 'README' | xargs rm -rf
      - git:
            repo: "https://gerrit.wikimedia.org/r/p/mediawiki/skins/{{ item.name }}.git"
            dest: "{{ mediawiki_root }}/skins/{{ item.name }}"
            version: "{{ mediawiki_version }}"
            depth: 1
            force: yes
            update: yes
        with_items: "{{ mediawiki_core_skins }}"
      - git:
            repo: "{{ item.repo }}"
            dest: "{{ mediawiki_root }}/skins/{{ item.name }}"
            version: "{{ item.version }}"
            depth: 1
            force: yes
            update: yes
        with_items: "{{ mediawiki_3rdparty_skins }}"
      - git:
            repo: "https://gerrit.wikimedia.org/r/p/mediawiki/extensions/{{ item.name }}.git"
            dest: "{{ mediawiki_root }}/extensions/{{ item.name }}"
            version: "{{ mediawiki_version }}"
            depth: 1
            force: yes
            update: yes
        with_items: "{{ mediawiki_core_extensions }}"
      - git:
            repo: "{{ item.repo }}"
            dest: "{{ mediawiki_root }}/extensions/{{ item.name }}"
            version: "{{ item.version }}"
            force: yes
            update: yes
        with_items: "{{ mediawiki_3rdparty_extensions }}"

- name: initializing Extensions and Skins
  block:
      - command: "git submodule update --init
            chdir={{ mediawiki_root }}/extensions/{{ item.name }}"
        with_items: "{{ mediawiki_core_extensions }}"
      - command: "php {{ mediawiki_root }}/composer.phar install
            chdir={{ mediawiki_root }}/extensions/{{ item.name }}"
        with_items: "{{ mediawiki_extension_dependency }}"
      - command:
            "php {{ mediawiki_root }}/composer.phar require {{ item.name }}:{{ item.version }} {{ item.option|default('') }}
            chdir={{ mediawiki_root }}"
        with_items: "{{ mediawiki_extension_bycomposer }}"

- name: install PHP/Parsoid services from repository
  block:
      - file:
            path: "{{ mediawiki_root }}/services"
            state: directory
            mode: 0644
      - git:
            repo: "https://gerrit.wikimedia.org/r/p/mediawiki/services/{{ item.name }}.git"
            dest: "{{ mediawiki_root }}/services/{{ item.name }}"
            version: "{{ item.version }}"
            depth: 1
            force: yes
            update: yes
        with_items: "{{ mediawiki_core_services }}"

- name: install customization files
  block:
      - file:
            path: "{{ mediawiki_root }}/conf.d"
            state: directory
            mode: 0644
      - copy:
            src: "{{ item.name }}"
            dest: "{{ item.dest }}"
            owner: root
            group: root
            mode: "{{ item.mode|default('0644') }}"
            backup: yes
        with_items: "{{ mediawiki_customization }}"

- name: do maintenance (cleanUp) before setup
  block:
      - shell: "{{ item }}
            chdir={{ mediawiki_root }}"
        with_items:
            - find . ! -name services | grep .git | xargs rm -rf
            - rm -f COPYING CREDITS FAQ HISTORY INSTALL README README.mediawiki UPGRADE
            - rm -rf docs tests
            - find {{ mediawiki_root }}/languages/i18n/ -type f -not \( -iname 'en*' -or -iname 'zh*' \) | xargs rm -f
            - find . -print | while read filename; do touch -d '{{ mediawiki_startdate }}' "$filename"; done
            - tar -czvf ../mediawiki_REL1{{ mediawiki_version.split('_')[1] }}_setup_$(date '+%Y%m%d').tar.gz ../$(basename {{ mediawiki_root }})
