# =============================================================================
#
# - This is part of Lifamily Library (Wiki) project
#
# - Copyright (C) 2010-2021     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: check {{ install_role_name }} installation status
  stat:
      path: "{{ mediawiki_root }}/RELEASE-NOTES-1.{{ mediawiki_version.split('_')[1] }}"
  register: inst_status
  tags: always

- name: debugging
  debug:
      msg:
          - "result:"
          - "install status:  {{ inst_status.stat.exists }}"
          - "the {{ install_role_name }} has installed, now starting configure process"
  when: inst_status.stat.exists == True
  tags: install

- import_tasks: install.yml
  when: inst_status.stat.exists == False
  tags: install

- name: check {{ install_role_name }} configuration
  stat:
      path: "{{ mediawiki_root }}/LocalSettings.php"
  register: conf_status
  tags: always

- name: debugging
  debug:
      msg:
          - "result:"
          - "configure status: {{ conf_status.stat.exists }}"
          - "the {{ install_role_name }} has configured, now starting upgrade process"
  when: conf_status.stat.exists == True
  tags: configure

- import_tasks: configure.yml
  when: conf_status.stat.exists == False
  tags: configure

- import_tasks: upgrade.yml
  when: conf_status.stat.exists == True
  tags: upgrade

- name: debugging
  debug:
      msg:
          - "result:"
          - "the {{ install_role_name }} has be upgraded, now you start the Website"
  tags: upgrade
